Cleanup localstack workflow

diff --git a/.github/workflows/localstack-test.yml b/.github/workflows/localstack-test.yml
--- a/.github/workflows/localstack-test.yml
+++ b/.github/workflows/localstack-test.yml
@@ -6,41 +6,42 @@ on:
     branches: [main]
 
 jobs:
-  test-with-localstack:
-    runs-on: ubuntu-latest
-    services:
-      localstack:
-        image: localstack/localstack:latest
-        ports:
-          - 4566:4566
-        options: >-
-          --health-cmd="curl -f http://localhost:4566/_localstack/health || exit 1"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
-    env:
-      AWS_ACCESS_KEY_ID: test
-      AWS_SECRET_ACCESS_KEY: test
-      AWS_DEFAULT_REGION: us-east-1
-      AWS_ENDPOINT_URL: http://localhost:4566
-      TF_VAR_aws_access_key: test
-      TF_VAR_aws_secret_key: test
-      TF_VAR_aws_region: us-east-1
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
-
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: 1.6.6
-
-      #- name: Configure AWS credentials
-      #  uses: aws-actions/configure-aws-credentials@v4
-      #  with:
-      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #    aws-region: us-east-1
+  ##test-with-localstack:
+##    runs-on: ubuntu-latest
+##    services:
+##      localstack:
+##        image: localstack/localstack:latest
+##        install-awslocal: 'true'
+##        ports:
+##          - 4566:4566
+##        options: >-
+##          --health-cmd="curl -f http://localhost:4566/_localstack/health || exit 1"
+##          --health-interval=10s
+##          --health-timeout=5s
+##          --health-retries=5
+##    env:
+##      AWS_ACCESS_KEY_ID: test
+##      AWS_SECRET_ACCESS_KEY: test
+##      AWS_DEFAULT_REGION: us-east-1
+##      AWS_ENDPOINT_URL: http://localhost:4566
+##      TF_VAR_aws_access_key: test
+##      TF_VAR_aws_secret_key: test
+##      TF_VAR_aws_region: us-east-1
+##    steps:
+##      - name: Checkout code
+##        uses: actions/checkout@v6
+##
+##      - name: Set up Terraform
+##        uses: hashicorp/setup-terraform@v3
+##        with:
+##          terraform_version: 1.6.6
+##
+##      #- name: Configure AWS credentials
+##      #  uses: aws-actions/configure-aws-credentials@v4
+##      #  with:
+##      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+##      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+##      #    aws-region: us-east-1
 
 #      - name: Configure AWS CLI for LocalStack
 #        run: |
@@ -60,29 +61,29 @@ jobs:
 #        working-directory: ./terraform_code
 #        run: terraform apply -auto-approve -var "aws_access_key=$AWS_ACCESS_KEY_ID" -var "aws_secret_key=$AWS_SECRET_ACCESS_KEY" -var "aws_region=$AWS_DEFAULT_REGION" -var "endpoint_url=$AWS_ENDPOINT_URL"
 #
-      - name: Validate resources in LocalStack
-        run: |
-          aws --endpoint-url=$AWS_ENDPOINT_URL s3 ls
-          # Add more aws cli checks as needed
+      ##- name: Validate resources in LocalStack
+      ##  run: |
+      ##    aws --endpoint-url=$AWS_ENDPOINT_URL s3 ls
+      ##    # Add more aws cli checks as needed
 
   test-action-full-options:
         runs-on: ubuntu-latest
-        needs: test-with-localstack
+        ##needs: test-with-localstack
         strategy:
           matrix:
             tf_action: [apply, destroy]
             aws_site_cdn_enabled: ['true', 'false']
             aws_r53_root_domain_deploy: ['true', 'false']
-        services:
-          localstack:
-            image: localstack/localstack:latest
-            ports:
-              - 4566:4566
-            options: >-
-              --health-cmd="curl -f http://localhost:4566/_localstack/health || exit 1"
-              --health-interval=10s
-              --health-timeout=5s
-              --health-retries=5
+        ##services:
+        ##  localstack:
+        ##    image: localstack/localstack:latest
+        ##    ports:
+        ##      - 4566:4566
+        ##    options: >-
+        ##      --health-cmd="curl -f http://localhost:4566/_localstack/health || exit 1"
+        ##      --health-interval=10s
+        ##      --health-timeout=5s
+        ##      --health-retries=5
         env:
           AWS_ACCESS_KEY_ID: test
           AWS_SECRET_ACCESS_KEY: test
@@ -91,7 +92,13 @@ jobs:
           LOCALSTACK: true
         steps:
           - name: Checkout code
-            uses: actions/checkout@v4
+            uses: actions/checkout@v6
+
+          - name: Start LocalStack
+            uses: LocalStack/setup-localstack@v0.2.3
+            with:
+              image-tag: 'latest'
+              install-awslocal: 'true'
 
           - name: Pre-create Terraform needed resources
             run: |
